//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Project.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test_Project.Shared.Resources.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age must be more than 18 years!.
        /// </summary>
        public static string AgeMustBeMoreThan18Years {
            get {
                return ResourceManager.GetString("AgeMustBeMoreThan18Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api is working fine!.
        /// </summary>
        public static string ApiStatus {
            get {
                return ResourceManager.GetString("ApiStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City doesn&apos;t exists!.
        /// </summary>
        public static string CityDoesnotExists {
            get {
                return ResourceManager.GetString("CityDoesnotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName is incorrect!.
        /// </summary>
        public static string FirstNameIsIncorrect {
            get {
                return ResourceManager.GetString("FirstNameIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender is incorrect!.
        /// </summary>
        public static string GenderIsIncorrect {
            get {
                return ResourceManager.GetString("GenderIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName is incorrect!.
        /// </summary>
        public static string LastNameIsIncorrect {
            get {
                return ResourceManager.GetString("LastNameIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number is not correct!.
        /// </summary>
        public static string MobileNumberIsNotCorrect {
            get {
                return ResourceManager.GetString("MobileNumberIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number type is not correct!.
        /// </summary>
        public static string MobileNumberTypeIsNotCorrect {
            get {
                return ResourceManager.GetString("MobileNumberTypeIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object already exists!.
        /// </summary>
        public static string ObjectAlreadyExists {
            get {
                return ResourceManager.GetString("ObjectAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object doesn&apos;t exists!.
        /// </summary>
        public static string ObjectDoesnotExists {
            get {
                return ResourceManager.GetString("ObjectDoesnotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonId is&apos;t declared!.
        /// </summary>
        public static string PersonIdIsNotDeclared {
            get {
                return ResourceManager.GetString("PersonIdIsNotDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrivateNumber is incorrect!.
        /// </summary>
        public static string PrivateNumberIsIncorrect {
            get {
                return ResourceManager.GetString("PrivateNumberIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RelatedPerson can&apos;t be same person!.
        /// </summary>
        public static string RelatedPersonCanNotBeSamePerson {
            get {
                return ResourceManager.GetString("RelatedPersonCanNotBeSamePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related person doesn&apos;t exists!.
        /// </summary>
        public static string RelatedPersonDoesnotExists {
            get {
                return ResourceManager.GetString("RelatedPersonDoesnotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation have already exists!.
        /// </summary>
        public static string RelationHaveAlreadyExists {
            get {
                return ResourceManager.GetString("RelationHaveAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation type name is not correct!.
        /// </summary>
        public static string RelationTypeNameIsNotCorrect {
            get {
                return ResourceManager.GetString("RelationTypeNameIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to request completed successfully!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
